<hr/>
<p>
   Recent comment(s)<br/>
  <table border="0" cellspacing="0" cellpadding="5" width="100%" class="tblPrint">
    <thead>
      <tr>
        <th width="15%" align="left">Name</th>
        <th width="25%" align="left">Role</th>
        <th width="15%" align="left">Date</th>
        <th width="15%" align="left">Action taken</th>
        <th width="30%" align="left">Comments</th>
      </tr>
    </thead>
    <tbody>
      $details$
    </tbody>
  </table>
</p>