<tr>
	<td class="$class$">$seq$</td>
  <td class="$class$">$item_code$</td>
	<td class="$class$">$description$</td>
	<td class="$class$" align="right">$quantity$</td>
	<td class="$class$">$uom$</td>
  <td class="$class$">$currency$</td>
  <td class="$class$" align="right">$unit_price$</td>
  <td class="$class$" align="right">$discount$</td>
  <td class="$class$" align="right">$additional_discount$</td>
  <td class="$class$" align="right">$total$</td>
  <td class="$class$">$vat_name$</td>
  <td class="$class$" align="right">$vat_amt_unit$</td>
  <td class="$class$" align="right">$vat_amount$</td>
  <td class="$class$" align="right">$subtotal$</td>
</tr>
$detail_cost_center$