<!-- FOOTER! -->
<table border="0" cellpadding="0" cellspacing="0" width="100%" class="x_min-width" style="table-layout:fixed">
  <tbody>
    <tr>
      <td bgcolor="#111010" align="center" style="padding:25px 15px 25px 15px">
        <table border="0" width="100%" cellspacing="0" cellpadding="0" align="center">
          <tbody>
            <tr>
              <td align="center" bgcolor="#111010" style="padding:0; border:0px">
                <table border="0" width="100%" cellspacing="0" cellpadding="0" align="center">
                  <tbody>
                    <tr style="">
                      <td align="center" bgcolor="#111010" style="font-size:14px; color:#dedede; line-height:23px; border:0px">
                        Please do not reply to this message. Replies to this message are routed to an unmonitored mailbox. If you have any questions, please do not hesitate to email $mailbox$.
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>