<style type="text/css">
  table.toc td p {
    margin: 0 0 5px 0;
    font-size: 7px !important;
  }
  ul.dashed {
    list-style: none;
    padding-left: 0;
  }
  
  li.toc{
    text-align: justify;
    font-family: Verdana, Geneva, sans-serif;
    font-size: 7px !important;
    margin-left: 10px;
    padding:0 !important;
  }

  /* Prevent nested li's from getting messed up */
  ul.dashed > li::before {
    content: "-";
    margin-left: -7px;
  }
  
  ul.toc, ol.toc{
    padding: 0 !important;
    margin: 0 !important;
  }
  
  ol.bracket {
      counter-reset: list;
      margin: 0;
  }

  ol.bracket > li {
      list-style: none;
      position: relative;
      margin-left: 13px !important;
  }

  ol.bracket > li:before {
      counter-increment: list;
      content: "(" counter(list, lower-alpha) ") ";
      position: absolute;
      margin-left: -13px;
  }
</style>
<table class="toc" border="0">
<tr>
  <td colspan="3" style="text-align: center" valign="top">
    <p style="font-size:14px">
      <strong>TERMS AND CONDITIONS</strong>
    </p>
  </td>
</tr>
<tr>
  <td>&nbsp;</td>
</tr>
<tr>
<td valign="top" width="47.5%">
  <p align="justify">
    <strong>Services.</strong> The Contractor shall provide and procure the delivery of the Goods/Services
    to the satisfaction of CIFOR pursuant to the terms of this Contract.
  </p>
  <p align="justify">
    <strong>Specification.</strong> The Goods delivered shall comply with the required specifications
    determined by CIFOR.
  </p>
  <p align="justify">
    <strong>Quality.</strong> The Goods shall be of merchantable quality and fit for any purpose which
    is made known by CIFOR or for which the Goods are commonly supplied.
  </p>
  <p align="justify">
    <strong>Free from Defects.</strong> The Goods shall be free from defects in material and
    workmanship.
  </p>
  <p align="justify">
    <strong>Sample or Description of Goods.</strong> Where the Goods are supplied by reference to a
    sample or description, the Goods shall correspond with the sample or description.
  </p>
  <p align="justify">
    <strong>Time is of the Essense.</strong> Time is of the essence for the delivery of goods and/or
    completion of the work described in the PO or in the project schedule. Any delay in
    the delivery of goods and/or completion of the work described therein shall
    constitute a material breach of this contract and the Contractor shall compensate the
    loss of time with the rate set out at xxx% for each postponement day
  </p>
  <p align="justify">
    If the Contractor is delayed in the performance of its services due to causes beyond
    the contractor's control, then the time allotted in the project schedule for the
    Contractor's Services shall be extended for the period of such delay or CIFOR shall
    authorize the Contractor to work overtime to make up for such lost time, and the
    Contractor's compensation shall be equitably adjusted.
  </p>
  <p align="justify">
    <strong>Variations.</strong> Variations may be initiated by CIFOR at any time prior to completion of the
    services by the Contractor. The Contractor shall submit the new project schedule and
    estimated cost of effecting the variation, based on the rates set out in the PO, to CIFOR
    and obtain the written confirmation and approval of CIFOR before starting work on the
    variation request.
  </p>
  <p align="justify">
    <strong>Giving Decisions.</strong> CIFOR shall give its approval for all sketches, designs,
    drawings, reports, documents, recommendations, requests, submissions and other
    matters referred by the Contractor to CIFOR or its authorized representative for
    decision within xxx days from the date of request, so as not to delay or disrupt the
    performance by the Contractor of the Services under this contract
  </p>
  <p align="justify">
    <strong>Breaches and Remedies.</strong> Any of the following will be considered as a breach or
    non-fulfillment of this contract on the part of the Contractor:
  </p>
  <ul class="dashed toc">
    <li class="toc">
      Non-disclosure of any relevant information, whether leading to the approval
      of the project by CIFOR, or whether pertaining to any aspect of the execution
      of the project
    </li>
    <li class="toc">
      Continual lack of progress on the project or lack of fulfillment of the
      Milestones in the agreed upon time
    </li>
  </ul>
  <p align="justify">
    In case of any breach of the obligations and warranties hereunder, CIFOR will have
    the following remedies:
  </p>
  <ol class="bracket toc">
    <li class="toc">to request corrective action for all remedial breaches; or</li>
    <li class="toc">
      to terminate the Contract in accordance with the termination provisions of
      this Contract
    </li>
  </ol>
  <p align="justify">
    <strong>Cancelation.</strong> This PO is deemed to be cancelled under the following
    circumstances:
  </p>
  <ul class="dashed toc">
    <li class="toc">
      The Contractor is unable to provide the parts or supplies or materials within 1
      (one) week after the issuance of this PO or the agreed upon time and no parts
      or supplies or material alternatives acceptable to CIFOR.
    </li>
    <li class="toc">
      Postponement of project work due to negligence of the contractor which
      brings money consequence to CIFOR
    </li>
  </ul>
  <p align="justify">
    The Contractor's total and cumulative liability for damages payable to CIFOR from
    any cause whatsoever and regardless of the form of action whether in contract or in
    tort or under statutory/strict liabilities or otherwise shall not exceed the amount as
    stated in the PO
  </p>
  <p align="justify">
    <strong>Insurance.</strong> The Contractor acknowledges and understands that CIFOR does not
    maintain and will not obtain insurance of any type to protect the Contractor against
    any loss, damage or injury that may in any way result from the Contractor's
    performance of the services/delivery of goods. The Contractor hereby releases
    CIFOR, and their employees from any and all liabilities for any loss, damage, injury
    or costs relating to the performance of the services/delivery of goods, CIFOR's use
    of the deliverables, or CIFOR's reliance of the services/goods provided hereunder.
  </p>
</td>
<td width="5%"></td>
<td valign="top" width="47.5%">
  <p align="justify">
    <strong>Termination.</strong>
  </p>
  <ol type="1" class="toc">
    <li class="toc">
      CIFOR may terminate this Contract with or without cause upon thirty (30)
      days prior written notice to the Contractor. Upon such termination, CIFOR
      shall pay the Contractor, at the rate set out in the PO for the Services
      satisfactorily performed/the Goods satisfactorily delivered up through the
      date of termination. Notwithstanding any provision in this Contract to the
      contrary, CIFOR will not be required to pay or reimburse the Contractor for
      any Services performed/Goods delivered or for expenses incurred by the
      Contractor after the date of the termination notice that could have been
      avoided or mitigated by the Contractor.
    </li>
    <li class="toc">
      Upon expiry of this Contract or upon termination by CIFOR in accordance
      with its terms, no compensation payment of any form will be payable to the
      Contractor including by reason of termination and the Contractor shall be
      solely responsible for any costs related to employees of the Contractor
      involved in performance of this Contract both during the term of this
      Contract and upon and following its termination.
    </li>
  </ol>
  <p align="justify">
    <strong>Governing Law and Settlement of Disputes.</strong> This Contract shall be governed by
    and construed in accordance with the laws of the Republic of Indonesia. In case of a
    dispute, the Parties shall convene and try to resolve such dispute in good faith. If the
    dispute cannot be resolved within [60] days after it came up, the dispute shall finally
    and conclusively settled by arbitration in accordance with the United Nations
    Commission on International Trade Law (UNCITRAL) Arbitration Rules
    (UNCITRAL Rules) as at present in force, except to the extent that there are any
    conflicts between the UNCITRAL Rules and the provisions of this Contract, the
    provisions of this Contract shall govern. The seat of the arbitral tribunal will be
    Jakarta, Indonesia. The language of the proceedings will be English.
  </p>
  <p align="justify">
    <strong>Force Majeure.</strong> Neither CIFOR nor the Contractor shall be liable for any delay in
    the performance of this Contract, nor for any other breach, nor for any loss or
    damage arising from uncontrollable forces such as fire, theft, storm, war, or any
    other force majeure event that could not have been reasonably avoided by exercise
    of due diligence.
  </p>
  <p align="justify">
    <strong>Assignment.</strong> The Contractor's interest in this Contract (including the Contractor's
    duties and obligations under this Contract, and the payables due to the Contractor under
    this Contract) may not be subcontracted, assigned, delegated, or otherwise transferred to
    a third party, in whole or in part.
  </p>
  <p align="justify">
    <strong>Entire Agreement; Modifications.</strong> This Contract supersedes all prior agreements,
    written or oral, between the Contractor and CIFOR and will constitute the entire
    agreement and understanding between the Parties with respect to the subject matter of
    this Contract. This Contract and each of its provisions will be binding upon the Parties
    and may not be waived, modified, amended or altered except it is made in writing and
    signed by both CIFOR and the Contractor.
  </p>
  <p align="justify">
    <strong>Corrupt Practices.</strong> Each Party hereby undertakes that, at the date of the entering
    into force of the Purchase, its directors, officers or employees have not offered,
    promised, given, authorized, solicited or accepted any undue pecuniary or other
    advantage of any kind (or implied that they will or might do any such thing at any
    time in the future) in any way connected with the Purchase and that it has taken
    reasonable measures to prevent subcontractors, agents or any other third parties,
    subject to its control or determining influence, from doing so.
  </p>
  <p align="justify">
    Corrupt Practice(s) shall include Bribery, Extortion or Solicitation, Trading in
    Influence and laundering the proceeds of these practices
  </p>
  <p align="justify">
    <strong>Safety &amp; Heath Procedure.</strong> The Contractor shall take every precaution against
    injuries to persons or damage to property. The Contractor shall establish and
    maintain safety procedures in connection with its work performed to satisfy its
    obligations under this Contract.
  </p>
</td>
</tr>
</table>