<tr>
  <td class="$class$">$item_code$</td>
  <td class="$class$">$description$</td>
  <td class="$class$" align="right">$quantity$</td>
  <td class="$class$">$uom$</td>
  <td class="$class$" align="right">$unit_price$</td>
  <td class="$class$" align="right">$estimated_cost$</td>
  <td class="$class$" align="right">$estimated_cost_usd$</td>
  <td class="$class$" align="right">$exchange_rate$</td>
  <td class="$class$" align="right">$attachment$</td>
</tr>
$detail_cost_center$