<div class="content" style="padding-bottom: 30px; margin-top:50px">
  <div class="content-center" style="font-weight: bold;">
    <p style="padding-bottom:20px">CONDITIONS </p>
  </div>
  <div style="padding-left:10%;padding-right:10%;">
    <ol>
      <li>
        The General Terms and Conditions of Services with $legal_entity$ apply to this transaction. Accessible via the link - <a href="https://www.worldagroforestry.org/sites/default/files/users/admin/General%20Terms%20and%20Conditions_0.pdf">General Terms and Conditions</a>   Form properly submitted constitutes the offer.
      </li>
      <li>The offer shall remain firm for minimum 30 days from the closing date unless otherwise stipulated by the seller.</li>
      <li>The buyer shall not be bound to accept the lowest or any other offer, and reserve the right to accept any offer in Part unless the contrary is stipulated by the seller. </li>
      <li>Samples of offers when required will be provided free, and if not destroyed during tests will, upon request, be returned at the seller’s expenses.</li>
    </ol>
  </div>
</div>

<div class="content" style="padding-bottom: 30px;">
  <div class="content-center" style="font-weight: bold;">
    <p style="padding-bottom:20px">INSTRUCTIONS </p>
  </div>
  <div  style="padding-left:10%;padding-right:10%;">
    <ol>
      <li>All entries must be typed or written in ink.   Mistakes must not be erased but should be crossed out and and corrections be made and initialed by the person signing the quotation.</li>
      <li>Quote on each item separately, and in units as specified.</li>
      <li>This form must be signed by a competent person and preferably it should also be rubber stamped. </li>
      <li>Each quotation should be submitted separately in separate email with the quotation Number indicated in email subject line. Descriptive literature or samples of the items offered may be forwarded with quotation.</li>
      <li>If you do not wish to quote, please endorse the reason on this form and return it, otherwise your name may be deleted from the buyer’s mailing list for the items listed here on. </li>
    </ol>
  </div>
</div>

<div class="content" style="padding-bottom: 150px;">
  <div class="content-center" style="font-weight: bold;">
    <p style="padding-bottom:20px">ANNEX 1- ITEM SPECIFICATIONS </p>
  </div>
  <div style="padding-left:10%;padding-right:10%;">
    <p >
      <b>Item A or Equivalent</b> with the following specifications:
    </p>
  </div>
</div>