<style type="text/css">
  p {   font-family: Verdana, Geneva, sans-serif;   font-size: 12px;  }
  .basefont {
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;
  border-bottom: #ddd solid 1px;
  border-right: #ddd solid 1px;
  padding:5px;  }

  .zebra {
  background-color: #E1F7F0;
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;
  border-bottom: #ddd solid 1px;
  border-right: #ddd solid 1px;
  padding:5px;  }

  .tableheader {
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;
  background-color: #00a46c;
  font-weight: bold;
  color: #FFF;   padding:5px;
  }
  .tableheader td {
  width:250px;
  }
  .tableheader2 {
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;
  background-color: #00a46c;
  font-weight: bold;   color: #FFF;   padding:5px;  }

  /* table {
  border-top: #ddd solid 1px;
  border-left: #ddd solid 1px;
  border-bottom: #ddd solid 1px;
  border-right: #ddd solid 1px;   }  */

  /* tr{   border-bottom: #ddd solid 1px;  }
  tr.row td {   border-bottom: #ddd solid 1px;
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;   }
  tr.norow td {   border-bottom:none;
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;   }
  tr.row td:first-child {
  width:250px;
  } */

  table {
  font-family: 'Verdana';
  font-size: 12px;
  border-collapse: collapse;
  width: 100%;
  }
  .table td, table th {
  border: 1px solid #ddd;
  padding: 8px;
  }

  td{
  vertical-align: top !important;
  }

  .email-footer {
  color:#f1be24;
  text-decoration:none;
  }

  .signature{
  font-family: Calibri;
  font-size: 9pt;
  }

  .header{
  padding-left: 5%;
  padding-bottom : 10px;
  }

  .company{
  font-family: Calibri;
  font-size: 14pt;
  color: #00a46c;
  }

  .line-header{
  border-color:  #00a46c;
  }

  .header{
  font-family: Verdana, Geneva, sans-serif;
  text-align: center;
  font-size: 14px;
  margin-bottom: 100px;
  font-weight: bold;
  }
  .version{
  font-family: Verdana, Geneva, sans-serif;
  margin-top: 50px;
  font-size: 12px;
  float: right;
  }

  .content {
  font-family: Verdana, Geneva, sans-serif;
  font-size: 12px;
  }
  .content-left {
  float: left;
  }

  .content-right{
  float: right;
  }

  .content-center{
  text-align: center;
  }

  .content-justify{
  text-align: justify;
  }

  .mb-2{
  -bottom:20px
  }
  
   .grid-container {
    font-family: Verdana, Geneva, sans-serif;
    font-size: 12px;
    display: grid;
    grid-template-columns: auto auto auto;
    /* padding: 10px; */
  }

  .grid-item {
    padding-top: 20px;
    padding-bottom: 20px;
  }
  
  @media print {
  .pagebreak {
  clear: both;
  page-break-after: always;
  /* break-after:page */
  }
  }
</style>