<table border="0" cellspacing="0" cellpadding="5" width="100%">
	<tr>
		<td colspan="2" class="tableheader" width="50px"></td>
	</tr>
	<tr>
		<td width="20%" class="zebra" valign="top">Original&nbsp;TO&nbsp;address(es)</td>
		<td width="80%" class="basefont">$emailTO$</td>
	</tr>
	<tr>
		<td width="20%" class="zebra" valign="top">Original&nbsp;CC&nbsp;address(es)</td>
		<td width="80%" class="basefont">$emailCC$</td>
	</tr>
	<tr>
		<td width="20%" class="zebra" valign="top">Date&nbsp;execution</td>
		<td width="80%" class="basefont">$dateExec$</td>
		</tr>
	  <tr>
		<td width="20%" class="zebra" valign="top">Email&nbsp;subject</td>
		<td width="80%" class="basefont">$emailSubject$</td>
	  </tr>
</table>