//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTree.WebForms.Modules.PurchaseRequisition
{


    public partial class Detail
    {

        /// <summary>
        /// recentCommentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.Usc.uscRecentComment recentCommentDetail;

        /// <summary>
        /// cancellationForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.Usc.uscCancellationForm cancellationForm;

        /// <summary>
        /// confirmationForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.UserConfirmation.uscSendConfirmation confirmationForm;

        /// <summary>
        /// prdetail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.PurchaseRequisition.uscPRDetail prdetail1;

        /// <summary>
        /// financialReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.PurchaseRequisition.uscFinancialReport financialReport1;

        /// <summary>
        /// confirmationList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.PurchaseRequisition.uscConfirmation confirmationList;

        /// <summary>
        /// historicalInformation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.PurchaseRequisition.uscHistoricalInformation historicalInformation1;
    }
}
