<tr>
  <td colspan="11" style="padding-left:5%; padding-top: 15px; padding-right: 15px; padding-bottom: 15px;">
    <table border="0" cellspacing="0" cellpadding="5" width="100%" class="tblPrint">
      <thead>
        <tr>
          <th width="15%" align="left" class="tableheader">Cost center</th>
          <th width="25%" align="left" class="tableheader">Work order</th>
          <th width="20%" align="left" class="tableheader">Entity</th>
          <th width="5%" align="left" class="tableheader">Legal entity</th>
          <th width="5%" align="left" class="tableheader">%</th>
          <th width="10%" align="left" class="tableheader">Amount ($currency_id$)</th>
          <th width="10%" align="left" class="tableheader">Amount (USD)</th>
          <th width="10%" align="left" class="tableheader">Remarks</th>
       </tr>  
    </thead>
    <tbody>
      $detail_cost_center_data$
    </tbody>
   </table>
  </td>
</tr>