//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procurement.PurchaseOrder
{


    public partial class Approval
    {

        /// <summary>
        /// recentCommentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.Usc.uscRecentComment recentCommentDetail;

        /// <summary>
        /// pod1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Procurement.PurchaseOrder.uscPurchaseOrderPrint pod1;

        /// <summary>
        /// povs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Procurement.PurchaseOrder.uscVendorSelection povs1;

        /// <summary>
        /// historicalInformation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.PurchaseRequisition.uscHistoricalInformation historicalInformation1;
    }
}
