//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Procurement.PurchaseOrder
{


    public partial class Detail
    {

        /// <summary>
        /// cancellationForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.Usc.uscCancellationForm cancellationForm;

        /// <summary>
        /// printOutEditform control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Procurement.PurchaseOrder.uscPrintOutEdit printOutEditform;

        /// <summary>
        /// confirmationForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.UserConfirmation.uscSendConfirmation confirmationForm;

        /// <summary>
        /// recentComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.Usc.uscRecentComment recentComment;

        /// <summary>
        /// historicalInformation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.PurchaseRequisition.uscHistoricalInformation historicalInformation1;

        /// <summary>
        /// financialReport1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Procurement.PurchaseOrder.uscFinancialReport financialReport1;

        /// <summary>
        /// confirmation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Procurement.PurchaseOrder.uscConfirmation confirmation1;
    }
}
