<p>
  <table border="0" cellspacing="0" cellpadding="5" width="100%" style="border: 0px;">
    <tr>
      <td width="30%">
        <p>
          <b>Purchase requisition code</b>
        </p>
      </td>
      <td width="70%">
        <p>$pr_no$</p>
      </td>
    </tr>
  </table>
</p>
<p>
  <table border="0" cellspacing="0" cellpadding="5" width="100%">
    <thead>
      <tr>
        <th width="20%" align="left" class="tableheader">Product code</th>
        <th width="50%" align="left" class="tableheader">Description</th>
        <th width="15%" align="right" class="tableheader">Quantity</th>
        <th width="15%" align="left" class="tableheader">UOM</th>
      </tr>
    </thead>
    <tbody>
      $item_details$
    </tbody>
  </table>
  <br/>
</p>