$Style$
$if(isTest)$
$TO_CC$
$endif$
<p>Dear all,</p>
<p>
  Please find below the list of PO(s) which has not been delivered yet.
</p>
<p>
  <table border="0" cellspacing="0" cellpadding="5" width="100%">
    <thead>
      <tr>
        <td width="10%" align="left" class="tableheader">OCS PO number</td>
        <td width="10%" align="left" class="tableheader">PO code</td>
        <td width="25%" align="left" class="tableheader">Supplier</td>
        <td width="25%" align="left" class="tableheader">Product</td>
        <td width="10%" align="right" class="tableheader">Quantity</td>
        <td width="5%" align="left" class="tableheader">Unit</td>
        <td width="15%" align="left" class="tableheader">Delivery date</td>
      </tr>
    </thead>
    <tbody>
      $details$
    </tbody>
  </table>
</p>
<p>Thank you.
</p>
<br>
 $Footer$
 