$Style$
$if(isTest)$
$TO_CC$
$endif$

<!-- header -->
<!-- <div class="header">
  <p>
    $letterHead$
  </p>
</div>
<hr  class="line-header"> -->
  <!-- end header -->
<p>
<br>
  To:
  <br/>$vendor_name$
  <br><br>Dear $cp_name$,
  <br><br>Please introduce me, $pro_name$, $pro_position$.<br/>
  We are sending you this email to ask if you could send us a quotation (your best offer) for product(s) with following detailed specification:
</p>
<p>
<br>
  <table border="0" cellspacing="0" cellpadding="5" width="100%">
    <thead>
      <tr>
        <th width="5%" align="left" class="tableheader">No</th>
        <th width="50%" align="left" class="tableheader">Description</th>
        <th width="15%" align="right" class="tableheader">Quantity</th>
        <th width="15%" align="left" class="tableheader">Unit or measurement</th>
      </tr>
    </thead>
    <tbody>
      $details$
    </tbody>
  </table>
</p>
<p>
  <br>
  Kindly send us your best quotation at least by $due_date$.<br><br>
  Thank you for your kind attention.
  <br><br>  Best regards,
</p>
  <p class="signature">
  <br>
    <b>Procurement Unit</b><br/>
    $signature$
    
    <a href="http://cifor.org/">cifor.org</a> | <a href="http://www.globallandscapesforum.org/">globallandscapesforum.org</a> | <a href="http://resilient-landscapes.org/">resilient-landscapes.org</a> <br/>
    <a href="http://www.cifor.org/" style="text-decoration:none">
      <img src="$cifor_icon_path$" alt="CIFOR logo.png" style="margin:5px;">
      </a>
    <a href="https://www.worldagroforestry.org/" style="text-decoration:none">
      <img src="$icraf_icon_path$" alt="ICRAF logo.png" style="margin:5px;">
      </a>
    <a href="http://www.globallandscapesforum.org/" style="text-decoration:none">
      <img src="$glf_icon_path$" alt="global landscapes forum logo.png" style="margin:5px;">
      </a>
    <a href="http://resilient-landscapes.org/" style="text-decoration:none">
      <img src="$rl_icon_path$" alt="resilient-landscapes logo.png" style="margin:5px;">
      </a><br/>
    CIFOR-ICRAF are <a href="http://cgiar.org">CGIAR Research Center</a>
  </p>