$Style$
$if(isTest)$
$TO_CC$
$endif$
<p>Dear all,</p>

<p>
  Below are the list of Request for quotation(s) which going to reach the due date in 1 working day.
</p>
<p>
  <table border="0" cellspacing="0" cellpadding="5" width="100%">
    <thead>
      <tr>
        <th width="15%" align="left" class="tableheader">RFQ code</th>
        <th width="40%" align="left" class="tableheader">Supplier</th>
        <th width="30%" align="left" class="tableheader">Contact person</th>
        <th width="15%" align="left" class="tableheader">Date sent to supplier</th>
      </tr>
    </thead>
    <tbody>
      $details$
    </tbody>
  </table>
</p>
<p>
  Thank you.
</p>
<br>
$Footer$