<tr>
	<td class="$class$">$item_description$</td>
	<td class="$class$" align="right">$qty_requested$</td>
	<td class="$class$" align="right">$total_previous_qty$</td>
  <td class="$class$" align="right">$send_quantity$</td>
  <td class="$class$" align="right">$qty_not_yet_delivered$</td>
  <td class="$class$" align="right">$quantity$</td>
  <td class="$class$" align="right">$qty_follow_up$</td>
</tr>