//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace myTree.WebForms.Modules.VendorSelection
{


    public partial class SingleSourcing
    {

        /// <summary>
        /// qadetail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::myTree.WebForms.Modules.QuotationAnalysis.uscQADetail qadetail1;
    }
}
